export const SubGameConstants = {
    LISTING_REQUEST: 'SUBGAME_LISTING_REQUEST',
    LISTING_SUCCESS: 'SUBGAME_LISTING_SUCCESS',
    LISTING_FAILURE: 'SUBGAME_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_SUBGAME_REQUEST',
    ADD_SUCCESS: 'ADD_SUBGAME_SUCCESS',
    ADD_FAILURE: 'ADD_SUBGAME_FAILURE',

    GET_REQUEST: 'GET_SUBGAME_REQUEST',
    GET_SUCCESS: 'GET_SUBGAME_SUCCESS',
    GET_FAILURE: 'GET_SUBGAME_FAILURE',

    UPDATE_REQUEST: 'UPDATE_SUBGAME_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUBGAME_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_SUBGAME_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_SUBGAME_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_SUBGAME_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_SUBGAME_FAILURE',
};
