export const UsersConstants = {
    LISTING_REQUEST: 'USERS_LISTING_REQUEST',
    LISTING_SUCCESS: 'USERS_LISTING_SUCCESS',
    LISTING_FAILURE: 'USERS_LISTING_FAILURE',

    PRIVILEGES_LISTING_REQUEST: 'PRIVILEGES_LISTING_REQUEST',
    PRIVILEGES_LISTING_SUCCESS: 'PRIVILEGES_LISTING_SUCCESS',
    PRIVILEGES_LISTING_FAILURE: 'PRIVILEGES_LISTING_FAILURE',

    ADD_USERS_REQUEST: 'ADD_USERS_REQUEST',
    ADD_USERS_SUCCESS: 'ADD_USERS_SUCCESS',
    ADD_USERS_FAILURE: 'ADD_USERS_FAILURE',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    UPDATE_USERS_REQUEST: 'UPDATE_USERS_REQUEST',
    UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
    UPDATE_USERS_FAILURE: 'UPDATE_USERS_FAILURE',
};
