export const EmailTemplateConstants = {
    LISTING_REQUEST: 'EMAIL_TEMPLATE_LISTING_REQUEST',
    LISTING_SUCCESS: 'EMAIL_TEMPLATE_LISTING_SUCCESS',
    LISTING_FAILURE: 'EMAIL_TEMPLATE_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_EMAIL_TEMPLATE_REQUEST',
    ADD_SUCCESS: 'ADD_EMAIL_TEMPLATE_SUCCESS',
    ADD_FAILURE: 'ADD_EMAIL_TEMPLATE_FAILURE',

    GET_REQUEST: 'GET_EMAIL_TEMPLATE_REQUEST',
    GET_SUCCESS: 'GET_EMAIL_TEMPLATE_SUCCESS',
    GET_FAILURE: 'GET_EMAIL_TEMPLATE_FAILURE',

    UPDATE_REQUEST: 'UPDATE_EMAIL_TEMPLATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_EMAIL_TEMPLATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_EMAIL_TEMPLATE_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_EMAIL_TEMPLATE_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_EMAIL_TEMPLATE_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_EMAIL_TEMPLATE_FAILURE',
};
