export const SmsTemplateConstants = {
    LISTING_REQUEST: 'SMS_TEMPLATE_LISTING_REQUEST',
    LISTING_SUCCESS: 'SMS_TEMPLATE_LISTING_SUCCESS',
    LISTING_FAILURE: 'SMS_TEMPLATE_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_SMS_TEMPLATE_REQUEST',
    ADD_SUCCESS: 'ADD_SMS_TEMPLATE_SUCCESS',
    ADD_FAILURE: 'ADD_SMS_TEMPLATE_FAILURE',

    GET_REQUEST: 'GET_SMS_TEMPLATE_REQUEST',
    GET_SUCCESS: 'GET_SMS_TEMPLATE_SUCCESS',
    GET_FAILURE: 'GET_SMS_TEMPLATE_FAILURE',

    UPDATE_REQUEST: 'UPDATE_SMS_TEMPLATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SMS_TEMPLATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_SMS_TEMPLATE_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_SMS_TEMPLATE_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_SMS_TEMPLATE_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_SMS_TEMPLATE_FAILURE',
};
