export const PlayerConstants = {
    LISTING_REQUEST: 'PLAYER_LISTING_REQUEST',
    LISTING_SUCCESS: 'PLAYER_LISTING_SUCCESS',
    LISTING_FAILURE: 'PLAYER_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_PLAYER_REQUEST',
    ADD_SUCCESS: 'ADD_PLAYER_SUCCESS',
    ADD_FAILURE: 'ADD_PLAYER_FAILURE',

    GET_REQUEST: 'GET_PLAYER_REQUEST',
    GET_SUCCESS: 'GET_PLAYER_SUCCESS',
    GET_FAILURE: 'GET_PLAYER_FAILURE',

    GET_PLAYER_BANK_REQUEST: 'GET_PLAYER_BANK_REQUEST',
    GET_PLAYER_BANK_SUCCESS: 'GET_PLAYER_BANK_SUCCESS',
    GET_PLAYER_BANK_FAILURE: 'GET_PLAYER_BANK_FAILURE',

    UPDATE_REQUEST: 'UPDATE_PLAYER_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_PLAYER_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_PLAYER_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_PLAYER_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_PLAYER_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_PLAYER_FAILURE',

    PLAYER_DEPOSIT_LISTING_REQUEST: 'PLAYER_DEPOSIT_LISTING_REQUEST',
    PLAYER_DEPOSIT_LISTING_SUCCESS: 'PLAYER_DEPOSIT_LISTING_SUCCESS',
    PLAYER_DEPOSIT_LISTING_FAILURE: 'PLAYER_DEPOSIT_LISTING_FAILURE',

    PLAYER_WITHDRAWAL_LISTING_REQUEST: 'PLAYER_WITHDRAWAL_LISTING_REQUEST',
    PLAYER_WITHDRAWAL_LISTING_SUCCESS: 'PLAYER_WITHDRAWAL_LISTING_SUCCESS',
    PLAYER_WITHDRAWAL_LISTING_FAILURE: 'PLAYER_WITHDRAWAL_LISTING_FAILURE',

    PLAYER_LOGIN_LISTING_REQUEST: 'PLAYER_LOGIN_LISTING_REQUEST',
    PLAYER_LOGIN_LISTING_SUCCESS: 'PLAYER_LOGIN_LISTING_SUCCESS',
    PLAYER_LOGIN_LISTING_FAILURE: 'PLAYER_LOGIN_LISTING_FAILURE',
};
