export const BetConstants = {
    LISTING_REQUEST: 'BET_LISTING_REQUEST',
    LISTING_SUCCESS: 'BET_LISTING_SUCCESS',
    LISTING_FAILURE: 'BET_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_BET_REQUEST',
    ADD_SUCCESS: 'ADD_BET_SUCCESS',
    ADD_FAILURE: 'ADD_BET_FAILURE',

    GET_REQUEST: 'GET_BET_REQUEST',
    GET_SUCCESS: 'GET_BET_SUCCESS',
    GET_FAILURE: 'GET_BET_FAILURE',

    UPDATE_REQUEST: 'UPDATE_BET_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_BET_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_BET_FAILURE',

    GET_STATUS_REQUEST: 'GET_BET_STATUS_REQUEST',
    GET_STATUS_SUCCESS: 'GET_BET_STATUS_SUCCESS',
    GET_STATUS_FAILURE: 'GET_BET_STATUS_FAILURE',

    PLAYER_BET_REQUEST: 'PLAYER_BET_REQUEST',
    PLAYER_BET_SUCCESS: 'PLAYER_BET_SUCCESS',
    PLAYER_BET_FAILURE: 'PLAYER_BET_FAILURE',

};
