export const DrawConstants = {
    LISTING_REQUEST: 'DRAW_LISTING_REQUEST',
    LISTING_SUCCESS: 'DRAW_LISTING_SUCCESS',
    LISTING_FAILURE: 'DRAW_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_DRAW_REQUEST',
    ADD_SUCCESS: 'ADD_DRAW_SUCCESS',
    ADD_FAILURE: 'ADD_DRAW_FAILURE',

    GET_REQUEST: 'GET_DRAW_REQUEST',
    GET_SUCCESS: 'GET_DRAW_SUCCESS',
    GET_FAILURE: 'GET_DRAW_FAILURE',

    UPDATE_REQUEST: 'UPDATE_DRAW_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_DRAW_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_DRAW_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_DRAW_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_DRAW_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_DRAW_FAILURE',
};
