export const DepositConstants = {
    LISTING_REQUEST: 'DEPOSIT_LISTING_REQUEST',
    LISTING_SUCCESS: 'DEPOSIT_LISTING_SUCCESS',
    LISTING_FAILURE: 'DEPOSIT_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_DEPOSIT_REQUEST',
    ADD_SUCCESS: 'ADD_DEPOSIT_SUCCESS',
    ADD_FAILURE: 'ADD_DEPOSIT_FAILURE',

    GET_REQUEST: 'GET_DEPOSIT_REQUEST',
    GET_SUCCESS: 'GET_DEPOSIT_SUCCESS',
    GET_FAILURE: 'GET_DEPOSIT_FAILURE',

    UPDATE_REQUEST: 'UPDATE_DEPOSIT_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_DEPOSIT_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_DEPOSIT_FAILURE',

    GET_STATUS_REQUEST: 'GET_DEPOSIT_STATUS_REQUEST',
    GET_STATUS_SUCCESS: 'GET_DEPOSIT_STATUS_SUCCESS',
    GET_STATUS_FAILURE: 'GET_DEPOSIT_STATUS_FAILURE',
};
