export const UserRoleConstants = {
    LISTING_REQUEST: 'USERS_ROLE_LISTING_REQUEST',
    LISTING_SUCCESS: 'USERS_ROLE_LISTING_SUCCESS',
    LISTING_FAILURE: 'USERS_ROLE_LISTING_FAILURE',

    PRIVILEGES_LISTING_REQUEST: 'PRIVILEGES_LISTING_REQUEST',
    PRIVILEGES_LISTING_SUCCESS: 'PRIVILEGES_LISTING_SUCCESS',
    PRIVILEGES_LISTING_FAILURE: 'PRIVILEGES_LISTING_FAILURE',

    ROLE_LISTING_REQUEST: 'ROLE_LISTING_REQUEST',
    ROLE_LISTING_SUCCESS: 'ROLE_LISTING_SUCCESS',
    ROLE_LISTING_FAILURE: 'ROLE_LISTING_FAILURE',

    ADD_USER_ROLE_REQUEST: 'ADD_USER_ROLE_REQUEST',
    ADD_USER_ROLE_SUCCESS: 'ADD_USER_ROLE_SUCCESS',
    ADD_USER_ROLE_FAILURE: 'ADD_USER_ROLE_FAILURE',

    GET_USER_ROLE_REQUEST: 'GET_USER_ROLE_REQUEST',
    GET_USER_ROLE_SUCCESS: 'GET_USER_ROLE_SUCCESS',
    GET_USER_ROLE_FAILURE: 'GET_USER_ROLE_FAILURE',

    UPDATE_USER_ROLE_REQUEST: 'UPDATE_USER_ROLE_REQUEST',
    UPDATE_USER_ROLE_SUCCESS: 'UPDATE_USER_ROLE_SUCCESS',
    UPDATE_USER_ROLE_FAILURE: 'UPDATE_USER_ROLE_FAILURE',
};
