export const DashboardConstants = {

    GET_REQUEST: 'GET_DASHBOARD_REQUEST',
    GET_SUCCESS: 'GET_DASHBOARD_SUCCESS',
    GET_FAILURE: 'GET_DASHBOARD_FAILURE',

    GET_GAME_ANALYTICS_REQUEST: 'GET_GAME_ANALYTICS_REQUEST',
    GET_GAME_ANALYTICS_SUCCESS: 'GET_GAME_ANALYTICS_SUCCESS',
    GET_GAME_ANALYTICS_FAILURE: 'GET_GAME_ANALYTICS_FAILURE',
};
