export const CategoryConstants = {
    LISTING_REQUEST: 'CATEGORY_LISTING_REQUEST',
    LISTING_SUCCESS: 'CATEGORY_LISTING_SUCCESS',
    LISTING_FAILURE: 'CATEGORY_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_FAILURE: 'ADD_CATEGORY_FAILURE',

    GET_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_FAILURE: 'GET_CATEGORY_FAILURE',

    UPDATE_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_CATEGORY_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
};
