export const WithdrawalConstants = {
    LISTING_REQUEST: 'WITHDRAWAL_LISTING_REQUEST',
    LISTING_SUCCESS: 'WITHDRAWAL_LISTING_SUCCESS',
    LISTING_FAILURE: 'WITHDRAWAL_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_WITHDRAWAL_REQUEST',
    ADD_SUCCESS: 'ADD_WITHDRAWAL_SUCCESS',
    ADD_FAILURE: 'ADD_WITHDRAWAL_FAILURE',

    GET_REQUEST: 'GET_WITHDRAWAL_REQUEST',
    GET_SUCCESS: 'GET_WITHDRAWAL_SUCCESS',
    GET_FAILURE: 'GET_WITHDRAWAL_FAILURE',

    UPDATE_REQUEST: 'UPDATE_WITHDRAWAL_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_WITHDRAWAL_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_WITHDRAWAL_FAILURE',

    GET_STATUS_REQUEST: 'GET_WITHDRAWAL_STATUS_REQUEST',
    GET_STATUS_SUCCESS: 'GET_WITHDRAWAL_STATUS_SUCCESS',
    GET_STATUS_FAILURE: 'GET_WITHDRAWAL_STATUS_FAILURE',
};
