export const CmsBannerConstants = {
    LISTING_REQUEST: 'CMS_BANNER_LISTING_REQUEST',
    LISTING_SUCCESS: 'CMS_BANNER_LISTING_SUCCESS',
    LISTING_FAILURE: 'CMS_BANNER_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_CMS_BANNER_REQUEST',
    ADD_SUCCESS: 'ADD_CMS_BANNER_SUCCESS',
    ADD_FAILURE: 'ADD_CMS_BANNER_FAILURE',

    GET_REQUEST: 'GET_CMS_BANNER_REQUEST',
    GET_SUCCESS: 'GET_CMS_BANNER_SUCCESS',
    GET_FAILURE: 'GET_CMS_BANNER_FAILURE',

    UPDATE_REQUEST: 'UPDATE_CMS_BANNER_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_CMS_BANNER_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_CMS_BANNER_FAILURE',

    GET_CMS_BANNER_TYPE_REQUEST: 'GET_CMS_BANNER_TYPE_REQUEST',
    GET_CMS_BANNER_TYPE_SUCCESS: 'GET_CMS_BANNER_TYPE_SUCCESS',
    GET_CMS_BANNER_TYPE_FAILURE: 'GET_CMS_BANNER_TYPE_FAILURE',
};
