export const ConfigConstants = {
    LISTING_REQUEST: 'CONFIG_LISTING_REQUEST',
    LISTING_SUCCESS: 'CONFIG_LISTING_SUCCESS',
    LISTING_FAILURE: 'CONFIG_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_CONFIG_REQUEST',
    ADD_SUCCESS: 'ADD_CONFIG_SUCCESS',
    ADD_FAILURE: 'ADD_CONFIG_FAILURE',

    GET_REQUEST: 'GET_CONFIG_REQUEST',
    GET_SUCCESS: 'GET_CONFIG_SUCCESS',
    GET_FAILURE: 'GET_CONFIG_FAILURE',

    UPDATE_REQUEST: 'UPDATE_CONFIG_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_CONFIG_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_CONFIG_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_CONFIG_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_CONFIG_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_CONFIG_FAILURE',
};
