export const CmsConstants = {
    LISTING_REQUEST: 'CMS_LISTING_REQUEST',
    LISTING_SUCCESS: 'CMS_LISTING_SUCCESS',
    LISTING_FAILURE: 'CMS_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_CMS_REQUEST',
    ADD_SUCCESS: 'ADD_CMS_SUCCESS',
    ADD_FAILURE: 'ADD_CMS_FAILURE',

    GET_REQUEST: 'GET_CMS_REQUEST',
    GET_SUCCESS: 'GET_CMS_SUCCESS',
    GET_FAILURE: 'GET_CMS_FAILURE',

    UPDATE_REQUEST: 'UPDATE_CMS_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_CMS_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_CMS_FAILURE',

    GET_CMS_LIST_REQUEST: 'GET_CMS_LIST_REQUEST',
    GET_CMS_LIST_SUCCESS: 'GET_CMS_LIST_SUCCESS',
    GET_CMS_LIST_FAILURE: 'GET_CMS_LIST_FAILURE',
};
