export const GameRunnerConstants = {
    LISTING_REQUEST: 'GAME_RUNNER_LISTING_REQUEST',
    LISTING_SUCCESS: 'GAME_RUNNER_LISTING_SUCCESS',
    LISTING_FAILURE: 'GAME_RUNNER_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_GAME_RUNNER_REQUEST',
    ADD_SUCCESS: 'ADD_GAME_RUNNER_SUCCESS',
    ADD_FAILURE: 'ADD_GAME_RUNNER_FAILURE',

    GET_REQUEST: 'GET_GAME_RUNNER_REQUEST',
    GET_SUCCESS: 'GET_GAME_RUNNER_SUCCESS',
    GET_FAILURE: 'GET_GAME_RUNNER_FAILURE',

    UPDATE_REQUEST: 'UPDATE_GAME_RUNNER_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_GAME_RUNNER_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_GAME_RUNNER_FAILURE',
};
