export const TransactionConstants = {
    LISTING_REQUEST: 'TRANSACTION_LISTING_REQUEST',
    LISTING_SUCCESS: 'TRANSACTION_LISTING_SUCCESS',
    LISTING_FAILURE: 'TRANSACTION_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_TRANSACTION_REQUEST',
    ADD_SUCCESS: 'ADD_TRANSACTION_SUCCESS',
    ADD_FAILURE: 'ADD_TRANSACTION_FAILURE',

    GET_REQUEST: 'GET_TRANSACTION_REQUEST',
    GET_SUCCESS: 'GET_TRANSACTION_SUCCESS',
    GET_FAILURE: 'GET_TRANSACTION_FAILURE',

    UPDATE_REQUEST: 'UPDATE_TRANSACTION_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_TRANSACTION_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_TRANSACTION_FAILURE',

    GET_STATUS_REQUEST: 'GET_TRANSACTION_STATUS_REQUEST',
    GET_STATUS_SUCCESS: 'GET_TRANSACTION_STATUS_SUCCESS',
    GET_STATUS_FAILURE: 'GET_TRANSACTION_STATUS_FAILURE',

    PLAYER_TRANSACTION_REQUEST: 'PLAYER_TRANSACTION_REQUEST',
    PLAYER_TRANSACTION_SUCCESS: 'PLAYER_TRANSACTION_SUCCESS',
    PLAYER_TRANSACTION_FAILURE: 'PLAYER_TRANSACTION_FAILURE',
};
