export const GameMasterConstants = {
    LISTING_REQUEST: 'GAME_MASTER_LISTING_REQUEST',
    LISTING_SUCCESS: 'GAME_MASTER_LISTING_SUCCESS',
    LISTING_FAILURE: 'GAME_MASTER_LISTING_FAILURE',

    ADD_REQUEST: 'ADD_GAME_MASTER_REQUEST',
    ADD_SUCCESS: 'ADD_GAME_MASTER_SUCCESS',
    ADD_FAILURE: 'ADD_GAME_MASTER_FAILURE',

    GET_REQUEST: 'GET_GAME_MASTER_REQUEST',
    GET_SUCCESS: 'GET_GAME_MASTER_SUCCESS',
    GET_FAILURE: 'GET_GAME_MASTER_FAILURE',

    UPDATE_REQUEST: 'UPDATE_GAME_MASTER_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_GAME_MASTER_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_GAME_MASTER_FAILURE',

    GET_ALL_REQUEST: 'GET_ALL_GAME_MASTER_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_GAME_MASTER_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_GAME_MASTER_FAILURE',
};
